config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :boards
  get 'new/edit'

  get 'sessions/new'

  resources :users
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  root 'static_pages#home'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'
  get '/bucket-list-budgeting', to: 'static_pages#budget'

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

end

app/models/board.rb
class Board < ApplicationRecord
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:lists, :name, :owner)
    end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_form.html.haml
= form_for @board do |f|
  - if @board.errors.any?
    #error_explanation
      %h2= "#{pluralize(@board.errors.count, "error")} prohibited this board from being saved:"
      %ul
        - @board.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :lists
    = f.text_field :lists
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :owner
    = f.text_field :owner
  .actions
    = f.submit 'Save'

app/views/boards/edit.html.haml
%h1 Editing board

= render 'form'

= link_to 'Show', @board
\|
= link_to 'Back', boards_path

app/views/boards/index.html.haml
%h1 Listing boards

%table
  %thead
    %tr
      %th Lists
      %th Name
      %th Owner
      %th

  %tbody
    - @boards.each do |board|
      %tr
        %td= board.lists
        %td= board.name
        %td= board.owner
        %td= link_to 'Show', board
        %td= link_to 'Edit', edit_board_path(board)
        %td= link_to 'Destroy', board, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Board', new_board_path

app/views/boards/new.html.haml
%h1 New board

= render 'form'

= link_to 'Back', boards_path

app/views/boards/show.html.haml
%p#notice= notice

%p
  %b Lists:
  = @board.lists
%p
  %b Name:
  = @board.name
%p
  %b Owner:
  = @board.owner

= link_to 'Edit', edit_board_path(@board)
\|
= link_to 'Back', boards_path
gitp