config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :boards
  get 'new/edit'

  get 'sessions/new'

  resources :users
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  root 'static_pages#home'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'
  get '/bucket-list-budgeting', to: 'static_pages#budget'

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

end

app/views/layouts/_footer.html.haml
%footer.footer
  .small
    %p Dao Board
  %nav
    %ul
      %li= link_to "About",   about_path
      %li= link_to "Contact", contact_path

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top
  .container.nav-container
    = link_to {image_tag('daoboard_logo.png', class: "logo")}
    %nav
      %ul.nav.navbar-nav.navbar-right
        %li= link_to "Home", root_path
        %li= link_to "About", about_path
        %li.dropdown
          %a.dropdown-toggle{href: "#", "data-toggle": "dropdown"}
            Features
            %b.caret
          %ul.dropdown-menu
            %li= link_to "Spending Prioritization", "#"
            %li= link_to "Weekly Planning Board", "#"
            %li= link_to "Long Term Horizons", "#"
        %li= link_to "Help", help_path
        - if logged_in?
          %li= link_to "Boards", boards_path
          %li= link_to "Users", users_path
          %li.dropdown
            %a.dropdown-toggle{href: "#", "data-toggle": "dropdown"}
              Account
              %b.caret
            %ul.dropdown-menu
              %li= link_to "Profile", current_user
              %li= link_to "Settings", edit_user_path(current_user)
              %li.divider
              %li= link_to "Logout", logout_path, method: :delete
        - else
          %li= link_to "Log in", login_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= full_title(yield(:title))
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    .container
      - flash.each do |type, msg|
        = content_tag(:div, msg, class: "alert alert-#{type}")
    = yield
  = render 'layouts/footer'
  = debug(params) if Rails.env.development?